name: DeployTest

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]

jobs:
  versionning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.genver.outputs.version }}
      release: ${{ steps.genver.outputs.release }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Generate Version
      id: genver
      run: |
        VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=${{ github.ref_name }}-pre --dev-branch=master)
        echo "::set-output name=version::$VERSION"
        echo "VERSION : $VERSION"
        RELEASE=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=${{ github.ref_name }} --dev-branch=master)
        echo "::set-output name=release::$RELEASE"
        echo "RELEASE : $RELEASE"

  buildProjects:
    runs-on: ubuntu-latest
    needs:
      - versionning
    env:
      GENVERSION: ${{ needs.versionning.outputs.version }}
      GENRELEASE: ${{ needs.versionning.outputs.release }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        source-url: https://pkgs.dev.azure.com/aneofr/ArmoniK/_packaging/ArmoniKPackages/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.PAT_AZURE}}

    # find . -name "*.csproj" | xargs -I % echo dotnet build % -c Release
    - name: Build the package
      run: |
        dotnet build -c Release ./Common/ArmoniK.DevelopmentKit.Common/ArmoniK.DevelopmentKit.Common.csproj
        dotnet build -c Release ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer/ArmoniK.DevelopmentKit.GridServer.Common.csproj
        dotnet build -c Release ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer/ArmoniK.DevelopmentKit.GridServer.csproj
        dotnet build -c Release ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Client/ArmoniK.DevelopmentKit.GridServer.Client.csproj
        dotnet build -c Release ./SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.csproj
        dotnet build -c Release ./SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.Client/ArmoniK.DevelopmentKit.SymphonyApi.Client.csproj
        dotnet build -c Release ./WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.csproj
        dotnet build -c Release ./WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/ArmoniK.DevelopmentKit.WorkerApi.Common.csproj
        dotnet build -c Release ./WorkerApi/tests/WorkerApiTests/WorkerApiTests.csproj

    # find . -name "*.csproj" | xargs -I % echo dotnet pack % -c Release -o /tmp/packages -p:PackageVersion=\$GENVERSION
    - name: Pack the package VERSION
      run: |
        dotnet pack ./Common/ArmoniK.DevelopmentKit.Common/ArmoniK.DevelopmentKit.Common.csproj -c Release -o /tmp/packages -p:PackageVersion=$GENVERSION
        dotnet pack ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer/ArmoniK.DevelopmentKit.GridServer.csproj -c Release -o /tmp/packages -p:PackageVersion=$GENVERSION
        dotnet pack ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Common/ArmoniK.DevelopmentKit.GridServer.Common.csproj -c Release -o /tmp/packages -p:PackageVersion=$GENVERSION
        dotnet pack ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Client/ArmoniK.DevelopmentKit.GridServer.Client.csproj -c Release -o /tmp/packages -p:PackageVersion=$GENVERSION
        dotnet pack ./SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.csproj -c Release -o /tmp/packages -p:PackageVersion=$GENVERSION
        dotnet pack ./SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.Client/ArmoniK.DevelopmentKit.SymphonyApi.Client.csproj -c Release -o /tmp/packages -p:PackageVersion=$GENVERSION
        dotnet pack ./WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/ArmoniK.DevelopmentKit.WorkerApi.Common.csproj -c Release -o /tmp/packages -p:PackageVersion=$GENVERSION

    - name: Store the package VERSION
      uses: actions/upload-artifact@v2
      with:
        name: prerelease-nugets
        path: /tmp/packages/*.nupkg
        retention-days: 5

    - name: Pack the package RELEASE
      if: ${{ github.ref == 'refs/heads/release' }}
      run: |
        dotnet pack ./Common/ArmoniK.DevelopmentKit.Common/ArmoniK.DevelopmentKit.Common.csproj -c Release -o /tmp/releases -p:PackageVersion=$GENRELEASE
        dotnet pack ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Common/ArmoniK.DevelopmentKit.GridServer.Common.csproj -c Release -o /tmp/releases -p:PackageVersion=$GENRELEASE
        dotnet pack ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer/ArmoniK.DevelopmentKit.GridServer.csproj -c Release -o /tmp/releases -p:PackageVersion=$GENRELEASE
        dotnet pack ./DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Client/ArmoniK.DevelopmentKit.GridServer.Client.csproj -c Release -o /tmp/releases -p:PackageVersion=$GENRELEASE
        dotnet pack ./SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.csproj -c Release -o /tmp/releases -p:PackageVersion=$GENRELEASE
        dotnet pack ./SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.Client/ArmoniK.DevelopmentKit.SymphonyApi.Client.csproj -c Release -o /tmp/releases -p:PackageVersion=$GENRELEASE
        dotnet pack ./WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/ArmoniK.DevelopmentKit.WorkerApi.Common.csproj -c Release -o /tmp/releases -p:PackageVersion=$GENRELEASE

    - name: Store the package RELEASE
      if: ${{ github.ref == 'refs/heads/release' }}
      uses: actions/upload-artifact@v2
      with:
        name: release-nugets
        path: /tmp/releases/*.nupkg
        retention-days: 5

    - name: Push the package
      run: |
        dotnet nuget push /tmp/packages/ArmoniK.*.nupkg --api-key AzureArtifacts

  buildWorker:
    runs-on: ubuntu-latest
    needs:
      - versionning
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        submodules: true

    - name: login
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u dhaneo1 --password-stdin

    - name: build
      run: |
        docker build -t dockerhubaneo/armonik_worker_dll:$VERSION -f WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/Dockerfile .

    - name: push
      run: |
        docker push dockerhubaneo/armonik_worker_dll:$VERSION

  testEndToEnd:
    needs:
      - versionning
      - buildProjects
      - buildWorker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: aneoconsulting/ArmoniK@main
        id: deploy-infra
        with:
          worker-image: dockerhubaneo/armonik_worker_dll
          worker-tag: ${{ needs.versionning.outputs.version }}

      - name: Run EndToEnd.Tests
        run: |
         export CPIP=$(kubectl get svc control-plane -n armonik -o custom-columns="IP:.spec.clusterIP" --no-headers=true)
         export CPPort=$(kubectl get svc control-plane -n armonik -o custom-columns="PORT:.spec.ports[*].port" --no-headers=true)
         export Grpc__Endpoint=http://$CPIP:$CPPort

         cd SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.Tests/EndToEnd.Tests/
         dotnet publish --self-contained -r linux-x64 -f net5.0

         sudo chown -R $USER:$USER /data
         cp ../packages/ArmoniK.EndToEndTests-v1.0.0.zip /data

         dotnet run -r linux-x64 -f net5.0

  release-packages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
      - versionning
      - testEndToEnd
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: release-nugets

      - name: Push the package
        run: dotnet nuget push ./ArmoniK.*.nupkg -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  release-images:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
      - versionning
      - testEndToEnd
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
      RELEASE: ${{ needs.versionning.outputs.release }}
    steps:
      - name: login
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u dhaneo1 --password-stdin

      - name: pull
        run: |
          docker pull dockerhubaneo/armonik_worker_dll:$VERSION

      - name: tag
        run: |
          docker tag dockerhubaneo/armonik_worker_dll:$VERSION dockerhubaneo/armonik_worker_dll:$RELEASE

      - name: push
        run: |
          docker push dockerhubaneo/armonik_worker_dll:$RELEASE

  tag:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
      - versionning
      - release-packages
    env:
      RELEASE: ${{ needs.versionning.outputs.release }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: tag
      run: |
        git tag $RELEASE
        git push origin $RELEASE
